### ISSUE TITLE
BO-52: Emitted code throws FieldAccessException when trying to access private fields in dynamic assembly

### ISSUE THREAD

**Issue by ninjaboy** [BullOak/BullOak#52]
# Type of issue: Bug 

Description
---

When acceptance tests are run by default without: [assembly: CollectionBehavior(DisableTestParallelization = true)] one of the exceptions occuring is:

```
System.FieldAccessException
Attempt by method 'StateGen_OwneddStateEmitter_IHoldHigherOrder.get_HigherOrder()' to access field 'StateGen_OwneddStateEmitter_IHoldHigherOrder._HigherOrder' failed.
   at StateGen_OwneddStateEmitter_IHoldHigherOrder.get_HigherOrder()
   at BullOak.Repositories.NEventStore.Test.Integration.StepDefinitions.ReconstituteEntitySteps.ThenHighOrderPropertyShouldBe(Int32 expectedHighOrder) in C:\Work\Open Source\BullOak\src\BullOak.Repositories.NEventStore.Test.Integration\StepDefinitions\ReconstituteEntitySteps.cs:line 44
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at BullOak.Repositories.NEventStore.Test.Integration.Specifications.ReconstituteStateFeature.ScenarioCleanup()
   at BullOak.Repositories.NEventStore.Test.Integration.Specifications.ReconstituteStateFeature.LoadStoredEntityWithSingleEvent() in C:\Work\Open Source\BullOak\src\BullOak.Repositories.NEventStore.Test.Integration\Specifications\ReconstituteState.feature:line 9
```

Research is needed to figure out what is causing this sort of issue

**Comment by skleanthous** [comment]
This issue seems to be related to https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/security-issues-in-reflection-emit which is weird, but by changing the fields emitted by the emitters to be public instead of private, everything works fine.

This does indeed merit a bit more investigation, but currently a fix for this will be made available in a new branch to investigate this in more detail.
