### ISSUE TITLE
BO-94: State type emitter does not emit inherited properties

### ISSUE THREAD

**Issue by iblazhko** [BullOak/BullOak#94]
Description
---

If a state interface (e.g. `IHoldState`) inherits some other interface (e.g. `IHoldBaseState`), only properties defined directly (i.e. in the `IHoldState` interface itself) are emitted, properties from base interface (`IHoldBaseState`) are not implemented.

**Version**: BullOak.Repositories 2.1.0
**Impact**: Critical
**Frequency**: Always

Proposal
---

Following unit tests should pass (code snippet below based on the existing `StateTypeEmitterTests` code)

``` C#
    public class StateTypeEmitterTests
    {
        public interface MyInterface
        {
            int MyValue { get; set; }
        }

        public interface IHavePropertiesViaAnotherInterface : MyInterface
        { }

        [Fact]
        public void EmitType_OfInterfaceWithOwnProperties_ShouldReturnTypeThatCanBeInstantiated()
        {
            //Arrange
            var emitter = new OwnedStateClassEmitter();
            var myType = StateTypeEmitter.EmitType(typeof(MyInterface), emitter);

            //Act
            var instance = Activator.CreateInstance(myType);

            //Assert
            instance.Should().NotBeNull();
        }

        [Fact]
        public void EmitType_OfInterfaceWithInheritedProperties_ShouldReturnTypeThatCanBeInstantiated()
        {
            //Arrange
            var emitter = new OwnedStateClassEmitter();
            var myType = StateTypeEmitter.EmitType(typeof(IHavePropertiesViaAnotherInterface), emitter);

            //Act
            var instance = Activator.CreateInstance(myType);

            //Assert
            instance.Should().NotBeNull();
        }
    }
```

Currently `EmitType_OfInterfaceWithOwnProperties_ShouldReturnTypeThatCanBeInstantiated` passes but `EmitType_OfInterfaceWithInheritedProperties_ShouldReturnTypeThatCanBeInstantiated` fails with error 

```
System.TypeLoadException
Method 'get_MyValue' in type 'StateGen_OwneddStateEmitter_IHavePropertiesViaAnotherInterface' from assembly 'BullOak.Repositories.Emitter.Group1, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at BullOak.Repositories.StateEmit.Emitters.BaseClassEmitter.EmitType(ModuleBuilder modelBuilder, Type typeToMake, String nameToUseForType)
   at BullOak.Repositories.StateEmit.Emitters.OwnedStateClassEmitter.EmitType(ModuleBuilder modelBuilder, Type typeToMake, String nameToUseForType)
   at BullOak.Repositories.StateEmit.Emitters.StateTypeEmitter.EmitType(Type typeToMake, BaseClassEmitter emitterToUse, String nameForClass)
   at BullOak.Repositories.Test.Unit.StateEmit.StateTypeEmitterTests.EmitType_OfInterfaceWithInheritedProperties_ShouldReturnTypeThatCanBeInstantiated()
```

Benefits
---

1. State interface can inherit from another interface (e.g. base interface with `Id` definition)

Risks
---

N/A

**Comment by skleanthous** [comment]
Hey @iblazhko thank you very much for your input. I'll start it immediately.
